### PR TITLE
@alloy => Update dependencies

### PR DESCRIPTION
**Pull request by kanaabe**
In order to get the latest on https://github.com/artsy/artsy-eigen-web-association/pull/7. 

Kind of weird that we include the modules this way, but I'm going to go with it in the interest of time. Also, I'm pretty unfamiliar with the deploy process for this app, do you think you can handle or show me? I saw it on OpsWorks but I didn't see deploy docs on this repo.

PS anyone who reads this/knows please show me the way!

### CODE REVIEW

**Comment by orta** [comment]
looking in the gitignore ( https://github.com/artsy/artsy-wwwify/blob/master/.gitignore#L22-L25 ) there's mention of a trend to keeping them in git. The article doesn't exist anymore, and https://github.com/npm/npm/issues/5722  implies it's not recommended

I bet with yarn those problems cease to exist.

**Comment by alloy** [comment]
Like mentioned on the Force ticket, I wonder if it’s really needed to update all the dependencies?

**Comment by craigspaeth** [comment]
Yeah we should probably stop checking in node modules—at one point that was a popular way to work around the occasional npm issue. Yarn could fix this, but given it's so simple and deployed on OpsWorks, it might be better to just leave it as is. @kanaabe It's been a while, but I'd be happy to pair on deploying this change.

**Comment by kanaabe** [comment]
Thanks for all the tips n facts. Would be nice to pair on getting this repo a fresh look @craigspaeth.

So for this one, I _think_ we need all the dependencies because the only packages involved in this repo are `artsy-eigen-web-association` and `morgan`. Pretty much all the changes are related to the sub-dependencies of `artsy-eigen-web-association`.

**Comment by alloy** [comment]
`artsy-eigen-web-association` has no dependency on `morgan`, so not sure how that could happen 🤔

**Comment by kanaabe** [comment]
Mm I mean in _this_ repo the dependencies are `artsy-eigen-web-association` and `morgan`: [see package.json](https://github.com/artsy/artsy-wwwify/blob/master/package.json#L20-L23).

Since we're checking everything in, the subdependencies of `artsy-eigen-web-association` are the ones that are bloated.

**Comment by alloy** [comment]
I’ve verified that the deployed staging setup works as expected with https://branch.io/resources/universal-links/. But unfortunately, as is generally the case, verifying it in the app requires some voodoo and as of yet it’s not being picked up yet… I’ll have to 🤔 a bit more about that.

In the meantime, I would suggest that @craigspaeth merges this when you sit down together to do the deploy as well, I’m a bit hesitant to merge many dependencies without reviewing all the changes.

**Pull request merged**
