### PR TITLE
Update Universal Links config to exclude all of Venice editorial.

### PR DESCRIPTION
**Pull request by alloy**
I don’t know why npm insist on upgrading all of these other dependencies, they shouldn’t be needed at all, but that appears to be how it’s historically always has been done in this repo.

### CODE REVIEW

**Comment by kanaabe** [comment]
👍 Thanks I had deployed www-ify yesterday without realizing it needed a dependency update. Will follow thru with another deploy.

**Comment by alloy** [comment]
Awesome, thanks 🙌

**Comment by alloy** [comment]
Btw, where/how do we actually deploy this app?

**Comment by kanaabe** [comment]
Oh! I will PR to the readme in a few. Opsworks is where we deploy.

**Pull request merged**
