### PR TITLE
fix: replace docker-compose extends keyword with Jinja2 template

### PR DESCRIPTION
**Pull request by izakp**
Required for Docker Compose v3 / Hokusai >= v0.5.12 compatibility

### CODE REVIEW

**Review by joeyAghion — APPROVED** [review]
In cases like these, I think it's simpler to just have the `build... context: ../` inline in the few locations. This seems correct enough though.

The build failure seems to have something to do with the `deploy` user's or folder permissions. 🤷‍♂️

**Comment by izakp** [comment]
Odd that the build suceeds tests pass for me when running `hokusai test` locally...  

This error would suggest permissions issues.  Can try with a `--no-cache` option to `yarn install`
```
error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/home/deploy/.cache/yarn/v6/npm-cliui-5.0.0-deefcfdb2e800784aa34f46fa08e06851c7bbbc5-integrity/node_modules/cliui/CHANGELOG.md' -> '/app/node_modules/cliui/CHANGELOG.md'".
```

**Comment by izakp** [comment]
Still not working here but working locally.  This thread seems to relate https://discuss.circleci.com/t/docker-build-fails-with-nonsensical-eperm-operation-not-permitted-copyfile/37364/23

**Comment by izakp** [comment]
FWIW re-ran tests on master and it fails with the same error https://app.circleci.com/pipelines/github/artsy/artsy-wwwify/176/workflows/9f8beb18-0c02-42ed-95c1-b9cb73c4e828/jobs/150 so unrelated to these changes 

cc @eessex @icirellik as this may pop up elsewhere

**Comment by izakp** [comment]
Linked from that CircleCI thread: https://support.circleci.com/hc/en-us/articles/360050934711 they recommend
```
- setup_remote_docker:
    version: 10.03.13
```
when using a node version 14.9.0 or later as a base image... so this would likely need to be done in an orb update and rolled out globally

**Comment by eessex** [comment]
I believe these tests are failing because hokusai context is not present on PR builds, it is missing config vars for the templates
Screen Shot 2020-10-28 at 1 38 52 PM

**Comment by izakp** [comment]
> it is missing config vars for the templates
Yes but note that is a warning - these config vars are not needed for test - only when rendering staging and production yml templates so should not affect PRs (this happens everywhere we test from a fork)

**Review by icirellik — APPROVED** [review]

**Pull request merged**
